CREATE TABLE IF NOT EXISTS `tblpermissions` (
  `AuthId` int NOT NULL AUTO_INCREMENT,
  `StuffId` varchar(15) NOT NULL,
  `Mg_St` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Ite` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Usr` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Usr` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Spl` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Spl` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Cus` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Cat` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Vw_Sal` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Cus` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Cat` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Pur` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Pur` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Tr_Pur` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Sal` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Sal` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Tr_Sal` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ad_Dis` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Ed_Dis` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Tr_Dis` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Vw_Rpt` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Bk_Db` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Rs_Db` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Chk_Exp` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Edt_Co_Info` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Programmers_Report` enum('Yes','No') NOT NULL DEFAULT 'No',
  `Settings` enum('Yes','No') NOT NULL DEFAULT 'No',
  PRIMARY KEY (`AuthId`),
  KEY `StuffId` (`StuffId`),
  CONSTRAINT `tblpermissions_ibfk_1` FOREIGN KEY (`StuffId`) REFERENCES `tblusers` (`StuffId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

