CREATE TABLE IF NOT EXISTS `tblretoutretin_details` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `Invoices` varchar(24) NOT NULL,
  `DrugsId` varchar(10) NOT NULL,
  `Units` varchar(20) NOT NULL,
  `Qty` decimal(10,2) NOT NULL,
  `CPrice` decimal(10,5) NOT NULL,
  `SPrice` decimal(10,2) NOT NULL,
  `Discount` decimal(10,2) NOT NULL,
  `Total` decimal(10,2) NOT NULL,
  `SupId` varchar(10) NOT NULL,
  `StuffId` varchar(15) NOT NULL,
  `Location` varchar(15) NOT NULL,
  `ExpiryDate` date NOT NULL,
  `AddedDate` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `DrugsId` (`DrugsId`),
  KEY `StuffId` (`StuffId`),
  KEY `SupId` (`SupId`),
  KEY `IX_tblretOutretIn_details_AddedDate` (`AddedDate`),
  CONSTRAINT `tblretOutretIn_details_ibfk_1` FOREIGN KEY (`DrugsId`) REFERENCES `tbldrugs` (`DrugsId`),
  CONSTRAINT `tblretOutretIn_details_ibfk_2` FOREIGN KEY (`StuffId`) REFERENCES `tblusers` (`StuffId`),
  CONSTRAINT `tblretOutretIn_details_ibfk_3` FOREIGN KEY (`SupId`) REFERENCES `tblsupplier` (`SupId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
